[package]
name = "kanbanrs"
version = "0.2.8"
edition = "2021"
repository = "https://github.com/epsilon-phase/kanbanrs/"
authors = ["Violet White"]
description = "A basic kanban task manager written with egui"
homepage = "https://github.com/epsilon-phase/kanbanrs/"
license = 'MIT'
include = [
    "**/*.rs",
    "assets/kanban icon.png",
    "assets/kanban icon 256.png",
    "assets/NotoSans-Regular.ttf",
    "assets/desktop_template.desktop",

]

[package.metadata.wix]
upgrade-guid = "08F7518F-464F-44FF-A58D-1E48F52F59DA"
path-guid = "1E655838-3829-48A6-9F58-DCA6D556746F"
license = false
eula = false

[dependencies]
eframe = { version = "0.34.2", features = ["persistence"] }
epaint = "0.34.2"
chrono = { version = "0.4.44", features = ["serde", "wasmbind"] }
serde = { version = "~1.0", features = ["derive"] }
serde_json = { version = "~1.0" }
rfd = { version = "0.14.1" }
nucleo-matcher = { version = "0.3.1" }
layout-rs = "0.1.2"
lazy_static = "~1"
parking_lot = { version = "0.12.3", features = ["serde"] }
circular-buffer = "0.1.9"
log = "0.4.22"
mimalloc = { version = "*", optional = true }

[dev-dependencies]
proptest = "1"

[features]
fast_allocator = ["dep:mimalloc"]

[target.'cfg(unix)'.dependencies]
xdg = "~2.5.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
clap = { version = "4.5.19", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlCanvasElement", "Storage"] }
web-time = "1"


[profile.small_as_can_be]
inherits = "release"
strip = true
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1


# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
